### PR TITLE
Add `new` constructor for `ScriptPurpose` members

### PR DESCRIPTION
**Pull request by sk-yagi**
We can construct a spending `ScriptPurpose` as follow:
```javascript
const output_id: TxOutputId = ...
const spending_sp: ScriptPurpose = ScriptPurpose::Spending::new(output_id)
```

### CODE REVIEW

**Comment by christianschmitz** [comment]
Everything looks correct.

Until now all the builtin enum variant constructors have been implemented differently though. For example:
```
DCert::new_register(...)
```

The reason for that is that user-defined enum methods (static and non-static) can only be defined on the enum type, not on the variant (that is also how it works in rust).

I suggest changing the constructors for consistency:
```
ScriptPurpose::new_minting()
ScriptPurpose::new_spending()
ScriptPurpose::new_rewarding()
ScriptPurpose::new_certifying()
```

**Review by christianschmitz — APPROVED** [review]
Nice contribution. Thanks!

**Comment by christianschmitz** [comment]
new Helios version: v0.8.4

**Comment by sk-yagi** [comment]
> Nice contribution. Thanks!

Much appreciated boss, keep up the great work!

**Pull request merged**
