### PR TITLE
Dev - added reward address getter and signData() method.

### PR DESCRIPTION
**Pull request by roschler**
Added a getter to return the current array of reward addresses as an array of StackAddress objects.  Also, added a signData() method so the user can sign messages with their wallet.  The signData() method accepts the message as a string and internally converts it to the hex string required by the wallet's signData() method before calling that method.

### CODE REVIEW

**Review by christianschmitz — CHANGES_REQUESTED** [review]
I'm sorry, there are too many changes and I can't accept this PR. Please first pull from the latest version of Helios (I'm about to release v0.16.5) and create another PR where I can clearly see the changes you made.

**Comment by roschler** [comment]
@christianschmitz Sure.  Would you mind telling which branch (and tag if any) so I don't make the same mistake?  Also, any other changes necessary beyond just pulling from the latest code version?

**Comment by christianschmitz** [comment]
The latest tag is v0.16.15

**Comment by roschler** [comment]
@christianschmitz Thanks, `main` or `dev` branch?

**Comment by christianschmitz** [comment]
always `main` branch please

**Comment by roschler** [comment]
Creating new PR based on `main` instead of `dev`, so closing this one.

**Pull request closed without merging**
